### PR TITLE
Post funtioning

### PR DESCRIPTION
**Pull request by MandasK**
# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
# Testing Instructions
``Git fetch origin ak-post``
``Git checkout origin ak-post``
``dotnet run`` from TabloidCLI folder
go into posts and test each section. should be able to list, add a new, edit a post and delete a post
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by chrismccolgan — APPROVED** [review]

**Review by chrismccolgan — CHANGES_REQUESTED** [review]
This one doesn't have the datetime stuff you did with Andy

**Comment by MandasK** [comment]
Should be there to see. I see it in the files changed.

**Review by chrismccolgan — APPROVED** [review]
Looks good

**Review by sfreeley — APPROVED** [review]
looks good, pulled down branch and tested

**Review by abernethyb — APPROVED** [review]
Looks good.  I would check the functionality of the "go back" option, but otherwise, looks good.  Good work!

**Pull request merged**
